In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print("hi")

hi

In [3]:
df=pd.read_csv("C:/Users/Windows/Desktop/projects/House Price India.csv")

In [4]:
df.columns

Index(['id', 'Date', 'No of bedrooms', 'No of bathrooms', 'living area',
       'lot area', 'No of floors', 'waterfront present', 'No of views',
       'house condition', 'house grade', 'house area(excluding basement)',
       'Area of the basement', 'Built Year', 'Renovation Year', 'Postal Code',
       'Lattitude', 'Longitude', 'living_area_renov', 'lot_area_renov',
       'No of schools nearby', 'Distance from the airport', 'Price'],
      dtype='object')

In [5]:
df.head()

,id,Date,No of bedrooms,No of bathrooms,living area,lot area,No of floors,waterfront present,No of views,house condition,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,No of schools nearby,Distance from the airport,Price
0,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
1,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
2,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
3,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
4,6762813105,42491,3,2.50,2600,4750,1.0,0,0,4,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [8]:
import pandas as pd
file_path=r"C:/Users/Windows/Desktop/projects/House Price India.csv"
def load_data(file_path):
    # Load dataset
    data = pd.read_csv(file_path)

    # Handle missing values
    data.fillna(method='ffill', inplace=True)

    # Convert categorical variables to numerical
    categorical_cols = ['waterfront present', 'house condition', 'house grade']
    data = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

    # Normalize numerical features if necessary
    numerical_cols = ['living area', 'lot area', 'No of floors', 'No of views', 
                      'house area(excluding basement)', 'Area of the basement', 
                      'Built Year', 'Renovation Year', 'No of schools nearby', 
                      'Distance from the airport']
    data[numerical_cols] = (data[numerical_cols] - data[numerical_cols].mean()) / data[numerical_cols].std()

    return data.head()

In [9]:
load_data(file_path)

,id,Date,No of bedrooms,No of bathrooms,living area,lot area,No of floors,No of views,house area(excluding basement),Area of the basement,...,house condition_5,house grade_5,house grade_6,house grade_7,house grade_8,house grade_9,house grade_10,house grade_11,house grade_12,house grade_13
0,6762810635,42491,4,2.50,0.885398,-0.292548,-0.004305,-0.304117,0.129925,1.590666,...,1,0,0,0,1,0,0,0,0,0
1,6762810998,42491,5,2.75,0.874625,-0.148037,-0.004305,-0.304117,1.329343,-0.660950,...,0,0,0,0,1,0,0,0,0,0
2,6762812605,42491,4,2.50,1.305558,0.735856,0.921207,-0.304117,1.809110,-0.660950,...,0,0,0,0,0,1,0,0,0,0
3,6762812919,42491,3,2.00,0.659158,-0.279363,-0.004305,-0.304117,0.093942,1.189388,...,0,0,0,0,1,0,0,0,0,0
4,6762813105,42491,3,2.50,0.540652,-0.272770,-0.929817,-0.304117,-0.121953,1.345440,...,0,0,0,0,0,1,0,0,0,0

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from joblib import dump
from src.data.data_loader import load_data

def train_model(data):
    # Define features and target
    X = data.drop(columns=['Price', 'id', 'Date'])
    y = data['Price']

    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize and train the model
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # Save the trained model
    dump(model, 'model/housing_price_model.joblib')

    return model

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from joblib import dump
from src.data.data_loader import load_data  # Ensure you have this function defined

def train_model(data):
    # Define features and target
    X = data.drop(columns=['Price', 'id', 'Date'])
    y = data['Price']

    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize and train the model
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # Save the trained model
    dump(model, 'model/housing_price_model.joblib')

    return model

# Load the dataset
file_path ="C:/Users/Windows/Desktop/projects/House Price India.csv"  # Replace with the actual path to your dataset
data = load_data(file_path)  # Load the data into the 'data' variable

# Call the train_model function with the loaded data
trained_model = train_model(data)

FileNotFoundError: [Errno 2] No such file or directory: 'path/to/your/dataset.csv'